### ISSUE TITLE
Upgrade to Torch 1.0.1

### ISSUE THREAD

**Issue by PonteIneptique** [emanjavacas/pie#16]
I have started looking at how well it does under 1.0.1. The focus of 1.0.1 was production readiness, so I am pretty much expecting better loading time.
You'd be okay with this change ?

> In 1.0, your code continues to work as-is, we’re not making any big changes to the existing API.

https://pytorch.org/blog/the-road-to-1_0/

**Comment by emanjavacas** [comment]
Sure, if you want to port it. Try running the tests and training some models. I haven't looked into it so far, so I dunno to what extent the api has changed.

**Comment by emanjavacas** [comment]
Btw. you can run the tests with `nosetest` from package `nose`.
```nosetests --all-modules --with-doctest`
and I just realized the tests need fixing.

**Comment by PonteIneptique** [comment]
Noted. My first look was : everything work but I'll do that more.
Anyway to have it connected to travis ?

**Comment by emanjavacas** [comment]
I've fixed the tests. I had to put app.py inside a main block to avoid nosetest executing it.
Re: travis. I thinking giving the amount of code that gets pushed and the number of people contributing, it would be more of a hassle to have it running, so I'd rather stay away from it for now. We can see in the future if it's necessary. Just make sure to run the tests before pushing submitting the PR.
