### ISSUE TITLE
Packaging ?

### ISSUE THREAD

**Issue by PonteIneptique** [emanjavacas/pie#17]
Hey, again,
I think this would be great to have something pip-able but I know you had your concern about it. I feel like torch on pip is in a good state. What do you think ?
Cheers,

**Comment by emanjavacas** [comment]
Hi, 

yes, that was mostly my concern, some of the dependencies need a bit of tweaking. But I wouldn't be against packaging if this would mean that more people get to try the package. The other thing is providing all the scripts (train.py, tag.py, evaluate.py, etc...). If you want to take care of that, I am fine.

**Comment by PonteIneptique** [comment]
I love packaging.
See you next week for a PR ;)
