### ISSUE TITLE
Using Cuda ?

### ISSUE THREAD

**Issue by mryolanda** [emanjavacas/pie#36]
Hi !
Thanks for your development!
I would like to experiment a bit pie, and you are mentioning the fact we can choose our device, but when I write :

`PIE_DEVICE=cuda:0`

I have the following error :

```bash
pie train config.json PIE_DEVICE=cuda:0
fatal: not a git repository (or any of the parent directories): .git
Usage: pie train [OPTIONS] CONFIG_PATH
Try "pie train --help" for help.
Error: Got unexpected extra argument (PIE_DEVICE=cuda:0)
```

I also have tried to change the device by default in pie/default_settings.json but the GPU is still not used.

Thanks !

**Comment by emanjavacas** [comment]
Hi! This kind of parameter passing through environment variables goes at the very beginning of the command. Try something like this:

```
PIE_DEVICE=cuda:0 pie train config.json
```

Using the config file should also work. Let me know if you get it to work!

**Comment by mryolanda** [comment]
Your solution works, thank you very much !
