### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by PonteIneptique** [emanjavacas/pie#4]
Hi there,

As you know, I have been looking at the repository and wanted to see how it goes. It seems some library are not installed but needed for the repo to run : 
- scipy
- termcolor

Just noting this here as it might be helpful down the line :) If I have other issues, should I wait for the things to be published or not ? (We have a new bigger corpus of ancient French data :) )

**Comment by emanjavacas** [comment]
Hey, thanks for your interest.

I'd say PIE is still not fully stable. I've been fixing certain issues recently. But if you want to use it, I'd recommend starting with the dev branch, which should be working fine (although it will be changing more often as well). If you do, it'd be cool to know if you encounter any issues. The features are quite similar to pandora, but the implementation is more mature and has more in the way of Multitask learning (although there are some important bits yet to be implemented in that direction). I keep a short description of all available settings in `pie/default_settings.json`.

**Comment by PonteIneptique** [comment]
Hi @emanjavacas ,
I did use the dev branch as I saw this was supposed to  be the most up to date branch. I am happy to continue to tell you when I encounter such issue :)
Best,
